### PR TITLE
Add support for thread based MDC

### PR DESCRIPTION
**Pull request by krishnamiriyala**

### CODE REVIEW

**Comment by AFriemann** [comment]
hey, i have a little health issue right now and won't be able to check this entirely this weekend. I'll get to it as soon as possible :)

**Comment by krishnambm** [comment]
@AFriemann Sure update me about the pull request, whenever you get chance ...

**Comment by krishnambm** [comment]
Any updates/comments on the pull request?

**Comment by AFriemann** [comment]
Hey there, sorry for the delay. We had a bunch of high priority issues in the last two weeks and on top of the cold i simply didn't have the time.

I'll take a look now and I think I see where you're trying to go, but I'll likely try to incorporate that in a cleaner way (no offense, really) with another change I need to do if that's alright with you.

I also included a license file (BSD v3) the other day, so you're now free to do with this/fork this at any time if you're unhappy with my solution :)

**Comment by AFriemann** [comment]
So I've been brooding over this a bit now and I'd like to at least give some feedback.

I won't go into too much detail in terms of quality. Theres some cleaning up to do (especially with the Formatter class), but that's really secondary.

My main gripe with is with the change in ThreadMDC. Storing the fields in the same object results in problems when leaving the Context. Some dummy code to clarify my point:

```
>>> logging.basicConfig(format='%(foos)s - %(message)s', handlers=[MDCHandler()])

>>> with ThreadMDC(foo='bar'):
...        logging.debug('test')
bar - test

>>> logging.debug('test')
bar - test
```

You can probably see the problem here.

However: I did some testing, benchmarking and all that and the current solution with merging dictionaries is unacceptably slow. So this definitely needs a solution.

Additionally I worked a lot with async python in the past weeks and noticed that this blows up the whole idea (fields are attached to log messages that shouldn't have them). I'm trying to figure out a solution to this, but I'm not there yet. 

I'll see that I put together a working integration of your ideas this weekend and I'll let you know if I do so you can at least use it.

**Comment by AFriemann** [comment]
Hey @krishnambm 

could you take a look at this https://github.com/AFriemann/mdc/pull/4

and let me know if it is sufficient for you?

**Pull request closed without merging**
