### PR TITLE
Add support for generators, argument catching and a bunch of other stuff

### PR DESCRIPTION
**Pull request by Stepland**
I use a new approach by patching the LogRecord factory that obsoletes the use of a special handler and a formatter, as importing `mdc` is now enough to patch `logging`

### CODE REVIEW

**Comment by Stepland** [comment]
Needs some nice testing as well

**Comment by AFriemann** [comment]
Hey, looks pretty good. I'll try to take a look as soon as I can!

**Comment by Stepland** [comment]
I also added a hack to sort contexts by creation time when retrieving context values to allow fields to be redefined when nesting contexts, see `test_nested_contexts()` for a demo.
It's implemented by adding a `time.time()` "delta" in the context name and then by sorting contexts by their names in `get_mdc_fields()`

**Comment by AFriemann** [comment]
damn this is really great, sorry I'm taking forever to do anything here. I'll put in a reminder for this evening to merge and publish this.

**Comment by AFriemann** [comment]
ok, turns out it still works - that was unexpected :D

could you check if everything works for you with the latest @Stepland? (`1.2.0.post2`)

**Comment by Stepland** [comment]
pip install'd and ran some manual tests, looks good !
Thanks a lot for merging :smile:

**Comment by Stepland** [comment]
Just realized the readme should be updated as well, I'll make a separate PR

**Pull request merged**
